---
name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true


      # WINDOWS
      - name: Cache conan
        if: startsWith(matrix.os, 'windows')
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-conan-root-${{ hashFiles('**/conanfile.txt') }}
          path: ~/.conan

      - name: Cache conan packages
        if: startsWith(matrix.os, 'windows')
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-conan-pkg-${{ hashFiles('**/conanfile.txt') }}
          path: C:/.conan/

      - name: Install dependencies (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
            REM We use this source (temporarily?) until choco has updated their version of conan
            choco install conan -y -s="https://api.bintray.com/nuget/anotherfoxguy/choco-pkg"
            refreshenv
        shell: cmd

      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
            call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            mkdir build
            cd build
            "C:\Program Files\Conan\conan\conan.exe" remote add conan-mpusz https://api.bintray.com/conan/mpusz/conan-mpusz
            "C:\Program Files\Conan\conan\conan.exe" install .. --build TBB
            cmake -G "Visual Studio 16 2019" -A x64 -DUSE_CONAN=ON -DUSE_CONAN_LIBS=true -DCMAKE_VERBOSE_MAKEFILE=true -DCMAKE_CONFIGURATION_TYPES=Release ..
            cmake --build . --config Release
            7z a conan-test2.zip D:/a/conan-test2/
        shell: cmd

      - name: Upload artifact (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v1
        with:
          name: conan-test2.zip
          path: build/conan-test2.zip
