---
name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true


      # WINDOWS
      - name: Cache conan
        if: startsWith(matrix.os, 'windows')
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-conan-root-${{ hashFiles('**/conanfile.txt') }}
          path: ~/.conan

      - name: Cache conan packages
        if: startsWith(matrix.os, 'windows')
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-conan-pkg-${{ hashFiles('**/conanfile.txt') }}
          path: C:/.conan/

      - name: Install dependencies (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
            REM We use this source (temporarily?) until choco has updated their version of conan
            choco install conan -y -s="https://api.bintray.com/nuget/anotherfoxguy/choco-pkg"
            refreshenv
        shell: cmd

      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
            call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            mkdir build
            cd build
            "C:\Program Files\Conan\conan\conan.exe" remote add conan-center "https://conan.bintray.com"
            "C:\Program Files\Conan\conan\conan.exe" install ..
            cmake ..
        shell: cmd

